ff4j/ff4j

- ff4j-aop/src/main/java/org/ff4j/aop/ContextLocation.java
- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
- ff4j-aop/src/main/java/org/ff4j/aop/Flip.java
- ff4j-aop/src/test/java/org/ff4j/aop/ContextService.java
- ff4j-aop/src/test/java/org/ff4j/aop/ContextServiceEnglishImpl.java
- ff4j-aop/src/test/java/org/ff4j/aop/ContextServiceFrenchImpl.java
- ff4j-aop/src/test/java/org/ff4j/aop/ContextStrategy.java
- ff4j-aop/src/test/java/org/ff4j/aop/FeatureFlippingThoughAopTest.java
- ff4j-core/src/main/java/org/ff4j/FF4j.java
@Flip annotation has a new argument to specify if the strategy evaluation needs a context, the values are:
- NONE: the strategy does not need context
- FF4J: the strategy will use a context stored in a ThreadLocal
- PARAMETER: the context is retrieved from the argument method, so the developer is free/responsible to pass the correct context (usefull to be thead-independant), or can reuse it to call a nested 'check'
> [aop] Evaluating the strategy with a context

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-core/src/main/java/org/ff4j/audit/EventPublisher.java
Currently there is no setter on FF4j to allow setting a customised
event publisher. Additionally, I have added constructors to allow
customising the executor used in the publisher and changing the
wait-time non-statically.
> Allow customisation of event publisher

- ff4j-core/src/main/java/org/ff4j/audit/EventWorker.java
This currently overwrites the thread name for the thread calling
EventPublisher.publish()
closes #54
> Do not rename current thread from EventPublisher

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-core/src/main/java/org/ff4j/audit/EventPublisher.java
This allows explicitly stopping the executor service
which is started for the event publishing.
closes #58
> Add shutdown methods to FF4J/EventPublisher

- ff4j-store-springjdbc/src/main/java/org/ff4j/store/rowmapper/FeatureRowMapper.java
- ff4j-store-springjdbc/src/main/java/org/ff4j/store/rowmapper/RoleRowMapper.java
L'interface ParameterizedRowMapper est déprécié dans spring 4.1 et supprimé dans spring 4.2 et a été créée à l'époque de spring 3 quand les generics n'éxistaient pas encore
> suppression de l'utilisation de l'interface ParameterizedRowMapper

- ff4j-aop/src/main/java/org/ff4j/spring/autowire/AutowiredFF4JBeanPostProcessor.java
- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/domain/FF4jStatusApiBean.java
squid:S2153 - Boxing and unboxing should not be immediately reversed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2153
George Kankava
> squid:S2153 - Boxing and unboxing should not be immediately reversed

- ff4j-store-jcache/src/main/java/org/ff4j/cache/FF4jJCacheProvider.java
- ff4j-store-jcache/src/main/java/org/ff4j/store/FeatureStoreJCache.java
- ff4j-store-jcache/src/main/java/org/ff4j/store/PropertyStoreJCache.java
- ff4j-strategy-drools/src/main/java/org/ff4j/drools/FF4jDroolsFlippingStrategy.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextAuthenticationManager.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/store/FeatureStoreHttp.java
squid:S2293 - The diamond operator ("<>") should be used.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2293
George Kankava
> squid:S2293 - The diamond operator ("<>") should be used

- ff4j-core/src/main/java/org/ff4j/audit/repository/InMemoryEventRepository.java
- ff4j-core/src/main/java/org/ff4j/audit/repository/JdbcEventRepository.java
- ff4j-strategy-drools/src/main/java/org/ff4j/drools/FF4jDroolsService.java
squid:S2095 - Resources should be closed.
squid:S128 - Switch cases should end with an unconditional "break" statement.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2095
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS128
George Kankava
> squid:S2095 - Resources should be closed

- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
- ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java
- ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
- ff4j-web/src/main/java/org/ff4j/web/FF4jInitServlet.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java
squid:S2696 - Instance methods should not write to "static" fields.
squid:S2275 - Printf-style format strings should not lead to unexpected behavior at runtime.
squid:S2178 - Short-circuit logic should be used in boolean contexts.
squid:S2226 - Servlets should not have mutable instance fields.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2696
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2275
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2178
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2226
George Kankava
> multiple code improvements: squid:S2696, squid:S2275, squid:S2178, squid:S2226

- ff4j-aop/src/main/java/org/ff4j/spring/namespace/FF4jNameSpaceHandler.java
- ff4j-core/src/main/java/org/ff4j/audit/graph/PieChart.java
- ff4j-core/src/main/java/org/ff4j/audit/graph/PieSector.java
- ff4j-core/src/main/java/org/ff4j/property/util/PropertyFactory.java
- ff4j-core/src/main/java/org/ff4j/utils/MappingUtil.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/FF4JApiApplication.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/FF4jApiApplicationJersey2x.java
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213
George Kankava
> squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
- ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java
- ff4j-core/src/main/java/org/ff4j/property/PropertyLogLevel.java
- ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthorizationFilter.java
squid:S2325 - "private" methods that don't access instance data should be "static"
squid:EmptyStatementUsageCheck - Empty statements should be removed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2325
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AEmptyStatementUsageCheck
George Kankava
> Multiple code improvements: squid:S2325, squid:EmptyStatementUsageCheck

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/domain/FF4jStatusApiBean.java
squid:S2185 - Silly math should not be performed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2185
George Kankava
> squid:S2185 - Silly math should not be performed

- ff4j-core/src/main/java/org/ff4j/audit/EventPublisher.java
- ff4j-core/src/main/java/org/ff4j/audit/EventRejectedExecutionHandler.java
- ff4j-core/src/main/java/org/ff4j/property/multi/AbstractPropertyMultiValued.java
- ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionFlipStrategy.java
- ff4j-core/src/test/java/org/ff4j/test/utils/ExceptionsTest.java
- ff4j-store-redis/src/main/java/org/ff4j/cache/FeatureCacheProviderRedis.java
- ff4j-store-redis/src/main/java/org/ff4j/store/FeatureStoreRedis.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleOperations.java
squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AClassVariableVisibilityCheck
George Kankava
> squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility

- ff4j-core/src/main/java/org/ff4j/audit/graph/BarChart.java
- ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java
- ff4j-core/src/main/java/org/ff4j/property/store/AbstractPropertyStore.java
- ff4j-core/src/main/java/org/ff4j/store/AbstractFeatureStore.java
- ff4j-core/src/main/java/org/ff4j/utils/JsonUtils.java
- ff4j-store-ehcache/src/main/java/org/ff4j/store/FeatureStoreEhCache.java
- ff4j-store-jcache/src/main/java/org/ff4j/store/FeatureStoreJCache.java
- ff4j-store-mongodb-v3/src/main/java/org/ff4j/store/mongodb/FeatureDocumentMapper.java
- ff4j-store-mongodb/src/main/java/org/ff4j/store/mongodb/FeatureDBObjectMapper.java
- ff4j-store-redis/src/main/java/org/ff4j/store/FeatureStoreRedis.java
- ff4j-store-springjdbc/src/main/java/org/ff4j/store/FeatureStoreSpringJdbc.java
- ff4j-test/src/main/java/org/ff4j/test/propertystore/PropertyStoreTestSupport.java
- ff4j-test/src/main/java/org/ff4j/test/store/FeatureStoreTestSupport.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleRenderer.java
- ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagDisable.java
- ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagEnable.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextAuthenticationManager.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextAuthenticationManager.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/FeatureStoreResource.java
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2864
George Kankava
> squid:S2864 - "entrySet()" should be iterated when both the key and value are needed

- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/domain/FF4jStatusApiBean.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/security/FF4jSecurityContext.java
squid:S1905 - Redundant casts should not be used.
squid:S106 - Standard outputs should not be used directly to log anything.
https://dev.eclipse.org/sonar/rules/show/squid:S1905
https://dev.eclipse.org/sonar/rules/show/squid:S106
George Kankava
> Multiple code improvements: squid:S1905, squid:S106

- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/store/FeatureStoreHttp.java
squid:S1192 - String literals should not be duplicated.
https://dev.eclipse.org/sonar/rules/show/squid:S1192
George Kankava
> squid:S1192 - String literals should not be duplicated

- ff4j-aop/src/main/java/org/ff4j/spring/placeholder/FF4jPropertiesPlaceHolderConfigurer.java
- ff4j-aop/src/main/java/org/ff4j/spring/placeholder/PropertiesPlaceHolderBeanDefinitionVisitor.java
This pull request is focused on resolving occurrence of Sonar rules
squid:ForLoopCounterChangedCheck - "for" loop stop conditions should be invariant.
squid:S1197 - Array designators "[]" should be on the type, not the variable.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AForLoopCounterChangedCheck
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1197
George Kankava
> Multiple code improvements: squid:ForLoopCounterChangedCheck, squid:S1197

- ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java
- ff4j-core/src/main/java/org/ff4j/property/Property.java
- ff4j-core/src/main/java/org/ff4j/strategy/PonderationStrategy.java
squid:S2130 - Parsing should be used to convert "Strings" to primitives.
https://dev.eclipse.org/sonar/rules/show/squid:S2130
George Kankava
> squid:S2130 - Parsing should be used to convert "Strings" to primitives

- ff4j-utils-json/src/main/java/org/ff4j/utils/json/PropertyJsonParser.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleOperations.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleRenderer.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/FF4jSwaggerConfiguration.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextHolder.java
squid:S1118 - Utility classes should not have public constructors.
https://dev.eclipse.org/sonar/rules/show/squid:S1118
George Kankava
> squid:S1118 Utility classes should not have public constructors

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-core/src/main/java/org/ff4j/cache/FF4jCacheProxy.java
- ff4j-core/src/main/java/org/ff4j/property/store/AbstractPropertyStore.java
- ff4j-core/src/main/java/org/ff4j/property/store/JdbcPropertyStore.java
- ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
This pull request is focused on resolving occurrence of Sonar rules
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S1905 - Redundant casts should not be used.
squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1905
https://dev.eclipse.org/sonar/rules/show/squid:S1155
George Kankava
> Multiple code improvements - squid:S1905, squid:S1155, squid:UselessParenthesesCheck

- ff4j-utils-json/src/main/java/org/ff4j/utils/json/FeatureJsonParser.java
- ff4j-utils-json/src/main/java/org/ff4j/utils/json/PropertyJsonParser.java
squid:S00122 - Statements should be on separate lines.
https://dev.eclipse.org/sonar/rules/show/squid:S00122
George Kankava
> squid:S00122 - Statements should be on separate lines

- ff4j-utils-json/src/main/java/org/ff4j/utils/json/FeatureJsonParser.java
- ff4j-utils-json/src/main/java/org/ff4j/utils/json/PropertyJsonParser.java
squid:S134 - Control flow statements "if", "for", "while", "switch" and "try" should not be nested too deeply.
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
https://dev.eclipse.org/sonar/rules/show/squid:S134
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
George Kankava
> Multiple code improvements - squid:S134, squid:UselessParenthesesCheck

- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java
- ff4j-aop/src/main/java/org/ff4j/spring/placeholder/FF4jPropertiesPlaceHolderConfigurer.java
- ff4j-aop/src/main/java/org/ff4j/spring/placeholder/PropertiesPlaceHolderBeanDefinitionVisitor.java
- ff4j-core/src/main/java/org/ff4j/utils/Util.java
- ff4j-store-ehcache/src/main/java/org/ff4j/store/PropertyStoreEhCache.java
- ff4j-store-mongodb-v3/src/main/java/org/ff4j/store/mongodb/FeatureDocumentMapper.java
- ff4j-utils-json/src/main/java/org/ff4j/utils/json/FeatureJsonParser.java
squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList".
squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used.
squid:S2583 - Conditions should not unconditionally evaluate to "TRUE" or to "FALSE".
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
https://dev.eclipse.org/sonar/rules/show/squid:S1319
https://dev.eclipse.org/sonar/rules/show/squid:S1149
https://dev.eclipse.org/sonar/rules/show/squid:S2583
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesChec …
> Multiple code improvements - squid:S1319, squid:S1149, squid:S2583, squid:UselessParenthesesCheck

- ff4j-store-neo4j/src/main/java/org/ff4j/neo4j/mapper/Neo4jMapper.java
- ff4j-store-neo4j/src/main/java/org/ff4j/neo4j/store/PropertyStoreNeo4j.java
- ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java
- ff4j-store-redis/src/main/java/org/ff4j/store/PropertyStoreRedis.java
- ff4j-strategy-drools/src/main/java/org/ff4j/drools/FF4jDroolsService.java
squid:S1444 - "public static" fields should be constant.
squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used.
squid:S1854 - Dead stores should be removed.
squid:S2293 - The diamond operator ("<>") should be used.
https://dev.eclipse.org/sonar/rules/show/squid:S1444
https://dev.eclipse.org/sonar/rules/show/squid:S1149
https://dev.eclipse.org/sonar/rules/show/squid:S1854
https://dev.eclipse.org/sonar/rules/show/squid:S2293
George Kankava
> Multiple code improvements - squid:S1444, squid:S1149, squid:S1854, squid:S2293

- ff4j-core/src/main/java/org/ff4j/utils/IOUtil.java
- ff4j-core/src/test/java/org/ff4j/test/utils/IOUtilsTest.java
- ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/FF4JApiApplication.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextAuthenticationManager.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/security/FF4jRolesResourceFilterFactory.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/api/security/FF4jSecurityContextFilter.java
- ff4j-webapi-jersey1x/src/test/java/org/ff4j/web/api/test/filter/SecurityFilterTest.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/FF4jApiApplicationJersey2x.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4JSecurityContextAuthenticationManager.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthenticationFilter.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthorizationFilter.java
- ff4j-webapi-jersey2x/src/test/java/org/ff4j/web/api/test/filter/SecurityAuthenticationFilterTest.java
squid:S1444 - "public static" fields should be constant.
squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility.
squid:S2696 - Instance methods should not write to "static" fields.
squid:S3008 - Static non-final field names should comply with a naming convention.
https://dev.eclipse.org/sonar/rules/show/squid:S1444
https://dev.eclipse.org/sonar/rules/show/squid:ClassVariableVisibilityCheck
https://dev.eclipse.org/sonar/rules/show/squid:S2696
https://dev.eclipse.org/sonar/rules/show/squid:S3008
George Kankava
> Multiple code improvements - squid:S1444, squid:ClassVariableVisibilityCheck, squid:S2696, squid:S3008

- ff4j-core/pom.xml
- ff4j-core/src/main/java/org/ff4j/audit/EventPublisher.java
- ff4j-core/src/main/java/org/ff4j/audit/EventRejectedExecutionHandler.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthenticationFilter.java
- ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/jersey2/store/FeatureStoreHttp.java
squid:S106 - Standard outputs should not be used directly to log anything.
https://dev.eclipse.org/sonar/rules/show/squid:S106
George Kankava
> squid:S106 - Standard outputs should not be used directly to log anything

- ff4j-core/src/main/java/org/ff4j/audit/Event.java
- ff4j-core/src/main/java/org/ff4j/audit/repository/InMemoryEventRepository.java
- ff4j-core/src/main/java/org/ff4j/audit/repository/JdbcEventRepository.java
- ff4j-store-neo4j/src/main/java/org/ff4j/neo4j/store/FeatureStoreNeo4J.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2864
George Kankava.
> squid:S2864 -  entrySet() should be iterated when both the key and value are needed

- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java
squid:S1989 - Exceptions should not be thrown from servlet methods.
This pull request removes 60 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1989
George Kankava
> squid:S1989 - Exceptions should not be thrown from servlet methods

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionNode.java
- ff4j-webapi-jersey1x/src/main/java/org/ff4j/web/jersey1/store/FeatureStoreHttp.java
squid:S2583 - Conditions should not unconditionally evaluate to "TRUE" or to "FALSE".
This pull request removes 70 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S2583
George Kankava
> squid:S2583 - Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"

- ff4j-aop/src/main/java/org/ff4j/spring/placeholder/FF4jPropertiesPlaceHolderConfigurer.java
- ff4j-store-jcache/src/main/java/org/ff4j/cache/FF4jJCacheProvider.java
- ff4j-web/src/main/java/org/ff4j/web/console/ImageProvider.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/FF4jResource.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/FeatureResource.java
- ff4j-webapi/src/main/java/org/ff4j/web/api/resources/PropertyResource.java
squid:S1166 - Exception handlers should preserve the original exception.
This pull request removes 60 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1166
George Kankava
> squid:S1166 - Exception handlers should preserve the original exception

- ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java
- ff4j-core/src/main/java/org/ff4j/core/FlippingExecutionContext.java
- ff4j-core/src/main/java/org/ff4j/property/multi/AbstractPropertyList.java
- ff4j-core/src/main/java/org/ff4j/property/store/JdbcPropertyStore.java
- ff4j-store-neo4j/src/main/java/org/ff4j/neo4j/mapper/Neo4jMapper.java
- ff4j-strategy-drools/src/main/java/org/ff4j/drools/FF4jDroolsService.java
squid:S2065 - Fields in non-serializable classes should not be "transient".
squid:ModifiersOrderCheck - Modifiers should be declared in the correct order.
squid:S1226 - Method parameters, caught exceptions and foreach variables should not be reassigned.
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
This pull request removes 50 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S2065
https://dev.eclipse.org/sonar/rules/show/squid:ModifiersOrderCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1226
https://dev.eclipse.org/sonar/rules/show/squid:S1213
Please let me know if you have any …
> Multiple code improvements - squid:S2065, squid:ModifiersOrderCheck, squid:S1226, squid:S1213

- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
- ff4j-core/src/main/java/org/ff4j/audit/EventPublisher.java
- ff4j-core/src/main/java/org/ff4j/audit/EventRejectedExecutionHandler.java
- ff4j-core/src/main/java/org/ff4j/audit/PublisherThreadFactory.java
squid:MethodCyclomaticComplexity - Methods should not be too complex.
squid:S00115 - Constant names should comply with a naming convention.
squid:S2142 - "InterruptedException" should not be ignored.
This pull request removes 57 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:MethodCyclomaticComplexity
https://dev.eclipse.org/sonar/rules/show/squid:S00115
George Kankava
> Multiple code improvements - squid:MethodCyclomaticComplexity, squid:S00115, squid:S2142, squid:S1161

- ff4j-core/src/main/java/org/ff4j/FF4j.java
- ff4j-core/src/main/java/org/ff4j/audit/proxy/FeatureStoreAuditProxy.java
squid:S1186 - Methods should not be empty.
squid:S00122 - Statements should be on separate lines.
squid:S1170 - Public constants should be declared "static final" rather than merely "final".
This pull request removes 116 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1186
https://dev.eclipse.org/sonar/rules/show/squid:S00122
https://dev.eclipse.org/sonar/rules/show/squid:S1170
George Kankava
> Multiple code improvements - squid:S1161, squid:S1186, squid:S00122, squid:S1170

- ff4j-cli/src/main/java/org/ff4j/cli/ansi/AnsiTerminal.java
- ff4j-core/src/main/java/org/ff4j/audit/repository/JdbcEventRepository.java
- ff4j-store-redis/src/main/java/org/ff4j/redis/RedisContants.java
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
squid:SwitchLastCaseIsDefaultCheck - "switch" statements should end with a "default" clause.
This pull request removes 55 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:SwitchLastCaseIsDefaultCheck
George Kankava
> Multiple code improvements - squid:S1161, squid:S1213, squid:SwitchLastCaseIsDefaultCheck

- ff4j-core/src/main/java/org/ff4j/audit/proxy/FeatureStoreAuditProxy.java
- ff4j-core/src/main/java/org/ff4j/audit/proxy/PropertyStoreAuditProxy.java
- ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java
- ff4j-store-redis/src/main/java/org/ff4j/redis/RedisContants.java
squid:ClassVariableVisibilityCheck - Class variable fields should not have public accessibility.
squid:S1444 - "public static" fields should be constant.
squid:S3008 - Static non-final field names should comply with a naming convention.
This pull request removes 120 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:ClassVariableVisibilityCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1444
https://dev.eclipse.org/sonar/rules/show/squid:S3008
Please let me …
> Multiple code improvements - squid:S1161, squid:ClassVariableVisibilityCheck, squid:S1444, squid:S3008

- ff4j-spring-boot-web-api/src/main/java/org/ff4j/spring/boot/web/api/resources/FeatureResource.java
The example pointed out in https://groups.google.com/d/msg/ff4j/1hzRkigHU3I/XQXv9q6wDQAJ (thanks for that anyway; it helped me a lot!!) does not work when using the ff4j-console against a sample service created with the `spring-boot-web-api` (instead of the non-spring web-api). This API expects `application/json` as value for the `Content-Type` header (even though a potential request body is ignored!) whereas the REST client in the console sends `plain/text` resulting in an `415 Unsupported Media Type` error.
This pull request removes all unnecessary `consumes=application/json` annotation elements from all methods that ignore the request body.
> Fix unsupported media type

- ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
- ff4j-core/src/main/java/org/ff4j/utils/JdbcUtils.java
`JdbcFeatureStore` overrides the `autoCommit` setting of the SQL `Connection` in order to handle its own transactions. However, it did not restore the previous value afterwards. As a consequence, feature toggle settings had not been stored immediately after their creation (because `autoCommit` had remained `false`. Only after a restart had the values been stored.
By restoring the previous `autoCommit` value changed feature toggle settings are stored now correctly.
> Restore autoCommit setting after transactions

- pom.xml
The ```logback.xml``` file should not be packaged into the jar artifacts, as it will pollute or override settings of projects using ff4j (this happened to us).
> Exclude logback.xml in jar packaging

- ff4j-web/src/main/java/org/ff4j/web/controller/HomeController.java
Fixed `TemplateProcessingException` caused by `Import XML`.
```
Servlet.service() for servlet [FF4jDispatcherServlet] in context with path [] threw exception
ognl.OgnlException: source is null for getProperty(null, "featureStore")
at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2327)
at ognl.ASTProperty.getValueBody(ASTProperty.java:114)
at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
at ognl.SimpleNode.getValue(SimpleNode.java:258)
at ognl.ASTChain.getValueBody(ASTChain.java:141)
at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
at ognl.SimpleNode.getValue(SimpleNode.java:258)
at ognl.Ognl.getValue(Ognl.java:494)
at ognl.Ognl.getValue(Ognl.java:458)
at org.thymeleaf.standard.expression.OgnlVariableExpressionEvaluator.evaluate(OgnlVariableExpressionEvaluator.java:1 …
```
> Fix problems importing xml

- ff4j-web/src/main/java/org/ff4j/web/FF4jServlet.java
- ff4j-web/src/main/java/org/ff4j/web/bean/HomeBean.java
- ff4j-web/src/main/java/org/ff4j/web/controller/FeaturesController.java
- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleRenderer.java
- ff4j-web/src/main/java/org/ff4j/web/utils/FileUtils.java
> Fix JavaDoc comments in ff4j-web

- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleOperations.java
Fixed `ArrayIndexOutOfBoundsException` caused by `Export XML`.
```
Servlet.service() for servlet [FF4jDispatcherServlet] in context with path [] threw exception
java.lang.ArrayIndexOutOfBoundsException: null
at java.lang.System.arraycopy(Native Method)
at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:328)
at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:405)
at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:393)
at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
at org.ff4j.web.embedded.ConsoleOperations.exportFile(ConsoleOperations.java:361)
at org.ff4j.web.controller.OperationsController.get(OperationsController.java:85)
at org.ff4j.web.FF4jDispatcherServlet.doGet(FF4jDispatcherServlet.java:54) …
```
> Fix problem exporting xml

- ff4j-web/src/main/resources/views/view-modal-properties.html
When editing and saving a property attached to a feature, the property dialog was closing and the page was immediately redirecting to the properties tab.    It looks like the featureId was being retrieved from the wrong modal.
> Issue 199 - Close property dialog and return to feature dialog

- ff4j-web/src/main/resources/views/view-modal-properties.html
It's because "Feature Description" and "Property Description" ID are the same "desc", so the "Feature Description" are cleared when initializing the property modal.
The problem was solved by changing the ID of "Property Description" to "pDesc".
> Fix problem "Feature Description" lost when opening property modal

- ff4j-web/src/main/java/org/ff4j/web/FF4jDispatcherServlet.java
If a user input in the Feature Name or Description, Property Name, Property Value multi-byte characters like `日本語` they are not properly encoded.
Fixed:
> Fix the character encoding problems in ff4j-web

- ff4j-web/src/main/resources/ff4j-messages.properties
- ff4j-web/src/main/resources/ff4j-messages_de.properties
- ff4j-web/src/main/resources/ff4j-messages_en.properties
I fixed some English messages I noticed.
> Improve english messages

- ff4j-core/src/main/java/org/ff4j/audit/repository/JdbcEventRepository.java
- ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
If you use JdbcFeatureStore with "audit" enabled, you can not add properties to the feature on `ff4j-web Administration Console`.
"Lock wait timeout exceeded; try restarting transaction" Occurs.
If "audit" is set to disabled, this problem does not occur.
> Fix "Lock wait timeout exceeded; try restarting transaction"

- ff4j-web/src/main/resources/static/js/ff4j.js
Fix to allow binding of multiple parameters separated by semicolon when opening feature edit dialog on ff4j-web Administration Console.
Now I can save multiple parameters, but opening a modal to edit again has the problem that only one parameter is bound.
> Fix to allow binding of multiple parameters separated by semicolon

- ff4j-store-hazelcast/pom.xml
For some reason the store-hazelcast subproject was pegged to ff4j-parent:1.6.5-SNAPSHOT, and not 1.6.6-SNAPSHOT, which is what the rest of the project is on. I've bumped it to be consistent with the rest of the project, so that I can continue building on master.
> Bump store-hazelcast parent pom version to 1.6.6-SNAPSHOT

- ff4j-core/src/main/java/org/ff4j/utils/JdbcUtils.java
PostgreSQL treats mixed case unquoted SQL identifiers as case insensitive and stores them in lower case.
Because of that, `isTableExists` returns false, although the table was created before with `createSchema`.
https://docs.oracle.com/javase/9/docs/api/java/sql/DatabaseMetaData.html#storesLowerCaseIdentifiers--
> PostgreSQL stores unquoted SQL identifiers in lower case

- ff4j-core/src/main/java/org/ff4j/core/FlippingStrategy.java
Hazelcast object depends on Serialization process and without Serializable  all operation related to Strategy is failing in hazelcast
> extends Serializable otherwise hazelcast implementation is failing

- ff4j-store-ehcache/src/main/java/org/ff4j/cache/FeatureCacheProviderEhCache.java
- ff4j-store-ehcache/src/main/java/org/ff4j/ehcache/FF4jEhCacheWrapper.java
I've run into a concurrency issue with the Ehcache integration:
```
net.sf.ehcache.ObjectExistsException: Cache ff4jCacheFeatures already exists
at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1237) ~[ehcache-2.10.4.jar!/:2.10.4]
at org.ff4j.cache.FeatureCacheProviderEhCache.initializeCache(FeatureCacheProviderEhCache.java:91) ~[ff4j-store-ehcache-1.7.1.jar!/:1.7.1]
at org.ff4j.cache.FeatureCacheProviderEhCache.getCacheFeatures(FeatureCacheProviderEhCache.java:184) ~[ff4j-store-ehcache-1.7.1.jar!/:1.7.1]
at org.ff4j.cache.FeatureCacheProviderEhCache.getFeature(FeatureCacheProviderEhCache.java:141) ~[ff4j-store-ehcache-1.7.1.jar!/:1.7.1]
at org.ff4j.cache.FF4jCacheProxy.read(FF4jCacheProxy.java:134) ~[ff4j-core-1.7.1.jar!/:1.7.1]
at …
```
> ensure that initialization of FeatureCacheProviderEhCache is thread-safe 

- ff4j-web/src/main/resources/static/js/ff4j.js
When errors are encountered from Ff4j, the Javascript error-handling code appears to be using an old name for the "ff4j_displayMessage" function.
> [Bugfix] Javascript calls renamed function 'displayMessage'.

- ff4j-store-consul/src/main/java/org/ff4j/consul/ConsulConnection.java
The constants in ConsulConstants.FF4J_PREFIXKEY already have a trailing slash.  When trying
to store audit logs in Consul, the current implementation tries to store with keys containing "//", which causes an error.
> [Bugfix] Remove extra '/' character when using FF4J_PREFIXKEY

- ff4j-spring-boot-autoconfigure/pom.xml
This dependency generate metadata needed to help Spring Boot with the
startup time.
> Add spring boot configuration processor dependency

- ff4j-web/src/main/java/org/ff4j/web/taglib/AbstractFeatureTag.java
- ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagDisable.java
- ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagEnable.java
- ff4j-web/src/main/resources/META-INF/tags/ff4j.tld
Hi,
This PR add an optional attribute to the taglib API to be able to store the feature condition into a variable (such as the `var` attribute of the `c:if` taglib).
It can be used like this:
```xml
<ff4j:enable featureid="my-awesome-feature" var="myAwesomeFeature"/>
<c:if test="${myAwesome && otherCondition}">
YOUR HTML CODE
</c:if>
```
This can be useful in a lot of use case when you only need a variable in a more complex test or when you want to evaluate the feature condition once and re-user this variable multiple times.
> feat: add a var attribute to the taglib API

- ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java
Prior to this fix, the following line throws a NPE in doPost() due to the servlet config not being properly stored in the 'config' member variable of GenericServlet since ConsoleServlet does not call it's super.init(servletConfig) method: 
getServletContext().setAttribute(FF4J_SESSIONATTRIBUTE_NAME, ff4j);
Reproduction for the error is just the following:
1) Access the web console for FF4J
2) Click the New Property button
3) Fill out the form with the following:
Name: test
Description: test
Type: org.ff4j.property.PropertyInt
Value: 0
4) Click the Create button
For the time being I've worked around this problem by using reflection to forcefully set the property in a subclass of ConsoleServlet:
```
public class CustomConsoleServlet extends ConsoleServlet {
@Override
public void …
```
> Fix NullPointerException in doPost

- ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedis.java
- ff4j-store-redis/src/test/java/org/ff4j/cache/RedisCacheManagerTestIT.java
As mentioned in #360 redis KEYS operation should be avoided as much as possible in production and should be replaced with scan instead
Here is a replacement proposal for Redis CacheManager implementation which was previously already using this way of operating for cleaning features.
> ff4j-store-redis: replace keys operations with scan

- ff4j-core/src/main/java/org/ff4j/cache/InMemoryCacheManager.java
I'm using InMemoryCacheManager because it is a simple implementation of
a FF4JCacheManager which nevertheless satifies my requirements. The only
concession that it makes is the long time to live. I would like to have
a shorter time to live. This is now possible by creating the cache
manager with an arbitrary time to live.
> Make time to live for cache entries configurable

- ff4j-store-redis/pom.xml
- ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedis.java
- ff4j-store-redis/src/main/java/org/ff4j/redis/RedisConnection.java
- pom.xml
Bumping the Jedis dependency version used by ff4j-redis-store so that it can be used in applications which has latest spring boot dependency i.e. 2.2.1.RELEASE.
> ff4j-redis-store | Bump redis.clients:jedis to 3.1.0 in /ff4j-store-redis

- ff4j-store-ehcache/pom.xml
- ff4j-store-neo4j/pom.xml
- pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
- ff4j-aop/src/main/java/org/ff4j/aop/FeatureAutoProxy.java
Using AnnotatedElementUtils instead of AnnotationUtils to allow composed annotations with @Flip. See Spring documentation for Class AnnotationUtils "For fine-grained support for meta-annotations with attribute overrides in composed annotations, consider using AnnotatedElementUtils's more specific methods instead."
> Using AnnotatedElementUtils instead of AnnotationUtils

- ff4j-core/src/main/java/org/ff4j/core/Feature.java
This PR deprecates the `fromJson` static method from `Feature` as it is currently not used and used to return null. I have added an `UnsupportedOperationException`. Let me know if this ok or if I should just leave it unchanged.
> Deprecate fromJson method from Feature

- ff4j-web/src/main/java/org/ff4j/web/FF4jDispatcherServlet.java
Issue: https://github.com/ff4j/ff4j/issues/437
For Get Request it will send redirect if there is missing trailing slash "<url>/ff-web/" is redirected to "<url>/ff-web/"
Key is this condition
"req.getServletPath().equals(req.getRequestURI())"
Can you see some issues? For me, it seems, that it should work well even for all projects, which already use it.
> Fix - Page cannot download resources on url without trainling slash.

- ff4j-store-mongodb-v3/src/main/java/org/ff4j/mongo/store/PropertyStoreMongo.java
- ff4j-store-mongodb-v3/src/test/java/org/ff4j/test/store/PropertyStoreMongoCollectionCore1Test.java
- ff4j-store-springjdbc/pom.xml
- ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/PropertyStoreSpringJdbc.java
- ff4j-store-springjdbc/src/test/java/org/ff4j/test/store/docker/SpringJdbcPropertyStoreTestDocker.java
- ff4j-test/src/main/java/org/ff4j/test/propertystore/PropertyStoreTestSupport.java
When using PropertyStoreSpringJdbc together with DBs that
are case insensitive, like PostgreSQL, an exception was
being thrown when trying to create the schema, if it had
already been created before.
This commit leverages the existing JdbcUtils that
addresses properly the issue.
Also this commit updates PropertyStoreMongo to use
`getCollection` instead of `createCollection` when
creating schema because Fakemongo does not implement
a `createCollection` method, leads to exceptions.
`getCollection` will create a collection if didn't exist
as per the documentation https://docs.mongodb.com/manual/reference/method/db.getCollection/#behavior
Closes https://github.com/ff4j/ff4j/issues/446
> Fix issue with case insensitive databases

- ff4j-core/src/main/java/org/ff4j/strategy/PonderationStrategy.java
This strategy javadoc appears to have been copied from ReleaseDateFlipStrategy.
This aim to rewrite it to represent it's real purpose
> Edit PonderationStrategy java doc to reflect it's real purpose

- ff4j-store-redis/pom.xml
- ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedis.java
- ff4j-store-redis/src/main/java/org/ff4j/cache/FF4jCacheManagerRedisLettuce.java
- ff4j-store-redis/src/test/java/org/ff4j/cache/it/PropertyStoreWithRedisCacheLettuceIT.java
- ff4j-store-redis/src/test/java/org/ff4j/cache/it/PropertyStoreWithRedisCacheTestIT.java
- ff4j-store-redis/src/test/java/org/ff4j/cache/it/RedisTestSupport.java
When using the "ClearCache" feature of ff4j-web-console with a Redis cache, the FF4J properties are not cleared.
There are two issues:
1. The clearProperties() implementation in FF4jCacheManagerRedis and FF4jCacheManagerRedisLettuce attempt to delete the keys by wildcard instead of scanning for matching keys
2. The FF4jCacheManagerRedisLettuce getKeys() implementation only scans the first result instead of scanning until finished.
This pull request makes the changes above, and uses testcontainers to provide tests for those changes.
Resolves #534
> issue 534 - Clear Cache Doesn't Clear Properties from Redis

- ff4j-core/src/main/java/org/ff4j/property/store/JdbcPropertyStore.java
- ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/FeatureStoreSpringJdbc.java
- ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/PropertyStoreSpringJdbc.java
Resolves issue #558 
The call to exists methods inside readGroup and readProperty costs one extra unnecessary DB call.
It was possible to make the method behave the same way while reducing this call.
> Remove unnecessary DB calls on readProperty and readGroup for Jdbc stores

- ff4j-security-spring/src/main/java/org/ff4j/security/SpringSecurityAuthorisationManager.java
When a spring boot project starts up it doesn't provide an `Authentication` object until it started up. 
If we had [such code](https://github.com/cbot59/spring-boot-ff4j-demo/commit/e6758ef5998c16ee28cb8163963a5ce54db370a0#diff-a64c1dc651d28eb9d18a38cac4248a09bd2ab32fc8debce9e44b2990be496529R16) it leads to spring boot project being failed to start up. 
Edit:
Just found out, the issue is coming caused by my [FF4JConfig](https://github.com/cbot59/spring-boot-ff4j-demo/commit/e6758ef5998c16ee28cb8163963a5ce54db370a0#diff-b44d89b238c5674011be19eb00bd32f19ef8c4b7ba405764655e7f4bd116cfa1R15) initialized audit as `true` leads to any feature created programmatically requires `Authentication` as a part of sending event for auditing purposes.
> Add NPE prevention on null authentication

- ff4j-web/src/main/resources/views/view-404.html
- ff4j-web/src/main/resources/views/view-audit.html
- ff4j-web/src/main/resources/views/view-featureUsage.html
- ff4j-web/src/main/resources/views/view-features.html
- ff4j-web/src/main/resources/views/view-header.html
- ff4j-web/src/main/resources/views/view-home.html
- ff4j-web/src/main/resources/views/view-infos.html
- ff4j-web/src/main/resources/views/view-messages.html
- ff4j-web/src/main/resources/views/view-modal-features.html
- ff4j-web/src/main/resources/views/view-modal-home.html
- ff4j-web/src/main/resources/views/view-modal-properties.html
- ff4j-web/src/main/resources/views/view-navbar.html
- ff4j-web/src/main/resources/views/view-properties.html
- ff4j-web/src/main/resources/views/view-settings.html
- ff4j-web/src/main/resources/views/view-timeSeries.html
Fixes deprecation warnings in ff4j-web, as mentioned in issue #701 
In Thymeleaf 3.1, th:include was deprecated and so is the unpacked fragment expression syntax.
https://www.thymeleaf.org/doc/articles/thymeleaf31whatsnew.html#deprecation-of-thinclude
th:insert behaves slightly differently, so some elements should be changed to th:block or explicitly use the th:remove="tag" attribute.
> Fix Thymeleaf deprecation warnings #701

- ff4j-core/src/main/java/org/ff4j/strategy/time/ReleaseDateFlipStrategy.java
- ff4j-core/src/main/java/org/ff4j/utils/TimeUtils.java
- ff4j-core/src/test/java/org/ff4j/test/strategy/ReleaseDateFlipStrategyMultiThreadTest.java
Replace SimpleDateFormat with DateTimeFormatter that is thread safe - fixes issue https://github.com/ff4j/ff4j/issues/705 which we see when we run multiple threads try to access all features that are backed up by DB. The unit test added exposes the issue in the original code as well
Closes : [Issue 705](https://github.com/ff4j/ff4j/issues/705)
Code contribution
> issue 705 Replace SimpleDateFormat with DateTimeFormatter that is thread safe

- ff4j-core/src/main/java/org/ff4j/property/store/JdbcPropertyStore.java
As described in https://github.com/ff4j/ff4j/issues/710, the create,update,delete operations on JdbcPropertyStore are now transactional, similar to JdbcFeatureStore
Closes : #710
> BUG-710 - transactional create,update,delete, like in JdbcFeatureStore
