ff4j/ff4j

ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java, ff4j-core/src/main/java/org/ff4j/FF4j.java, ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java, ff4j-core/src/main/java/org/ff4j/property/store/JdbcPropertyMapper.java, ff4j-utils-json/src/main/java/org/ff4j/utils/json/FeatureJsonParser.java, ff4j-web/src/main/java/org/ff4j/web/FF4jInitServlet.java, ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleOperations.java, ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java
Just ran a sed over the files to fix the spelling of 'instantiate'.
=> Fix typos in spelling of instantiate

README.md
Just a few minor corrections in the README text.
=> Improve the English of README.md

ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java, ff4j-core/src/main/java/org/ff4j/conf/XmlParser.java, ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureMapper.java, ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionNode.java, ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionParser.java, ff4j-test/src/main/java/org/ff4j/test/store/FeatureStoreTestSupport.java, ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleOperations.java, ff4j-web/src/main/java/org/ff4j/web/embedded/ConsoleServlet.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1854 - Dead stores should be removed.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1854
George Kankava
=> squid:S1854 - Dead stores should be removed

ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/filter/ApiKey.java, ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/filter/ApiKeyValidatorFilter.java, ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/filter/JerseyApplicationEventListener.java, ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/filter/JerseyRequestEventListener.java, ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthorizationFilter.java, ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/store/FeatureStoreHttp.java
squid:S00105 - Tabulation characters should not be used.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
George Kankava
=> squid:S00105 - Tabulation characters should not be used

ff4j-store-mongodb-v3/pom.xml, ff4j-store-mongodb/pom.xml, pom.xml
Hi,
I can't compile ff4j because of the missing "version" in root pom.
Upgrade fongo version (and go to 3.2.X drivers versions)
=> upgrade mongo

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java, ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java
common-java:DuplicatedBlocks - Source files should not have any duplicated blocks.
This pull request removes 60 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/common-java:DuplicatedBlocks
George Kankava
=> common-java:DuplicatedBlocks - Source files should not have any duplicated blocks

ff4j-core/src/main/java/org/ff4j/audit/repository/InMemoryEventRepository.java
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
squid:S134 - Control flow statements "if", "for", "while", "switch" and "try" should not be nested too deeply.
This pull request removes 65 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
https://dev.eclipse.org/sonar/rules/show/squid:S134
George Kankava
=> Multiple code improvements - squid:S1161, squid:CommentedOutCodeLine, squid:S134

ff4j-aop/src/main/java/org/ff4j/spring/placeholder/PropertiesPlaceHolderBeanDefinitionVisitor.java, ff4j-core/src/main/java/org/ff4j/property/PropertyString.java, ff4j-core/src/main/java/org/ff4j/strategy/el/ExpressionParser.java, ff4j-strategy-drools/src/main/java/org/ff4j/drools/FF4jDroolsService.java
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
This pull request removes 90 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
George Kankava
Unwatch this pull request
Learn more
=> squid:CommentedOutCodeLine - Sections of code should not be "commented out"

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
By using JdbcFeatureStore, we identify that some memory leaks in jdbc use.
Some resultset and prepared statements are not closed, leaving some cursors still opened on database side.
=> JDBC feature store memory leak

ff4j-store-redis/src/main/java/org/ff4j/redis/RedisContants.java, ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java, ff4j-web/src/main/java/org/ff4j/web/bean/HomeBean.java, ff4j-web/src/main/resources/views/view-home.html
- Adding the implementation for the monitoring section with Redis as the persistence.
- Changed the storing mechanism using zset in Redis to be able to query based on time.
- Minor adjustments to the Cache name and image directory.
=> Adding implementation to the Redis event repository

ff4j-web/src/main/resources/views/view-modal-properties.html
Exception occurs when opening `/features` or `/properties` page.
```
Servlet.service() for servlet [FF4jDispatcherServlet] in context with path [] threw exception
org.xml.sax.SAXParseException: ...
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentD …
```
=> Fix invalid html comment

ff4j-core/src/main/java/org/ff4j/cache/Store2CachePollingWorker.java
Catch exceptions when polling features, properties from target store.Otherwise, subsequent polling will be suppressed on any exceptions since ScheduledExecutorService being used in the scheduler.
=> Catch exceptions when polling features, properties from target store.

ff4j-web/src/main/resources/ff4j-messages.properties, ff4j-web/src/main/resources/ff4j-messages_en.properties, ff4j-web/src/main/resources/ff4j-messages_ja.properties, ff4j-web/src/main/resources/views/view-audit.html, ff4j-web/src/main/resources/views/view-featureUsage.html, ff4j-web/src/main/resources/views/view-navbar.html, ff4j-web/src/main/resources/views/view-settings.html, ff4j-web/src/main/resources/views/view-timeSeries.html
Improvement of Japanese messages with continuation of #209.
Therefore, I extracted several labels into a message property file so that it can be multilingualized.
=> improve japanese messages.

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
=> [issue 224] missing commit

ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java
proposition of correction.
I tested it on H2 and Oracle.
This PR should be tested against other SQL databases.
=> [issue 230] invalid semicolons in sql statement

.gitignore, ff4j-parent.iml, ff4j-spring-boot-autoconfigure/pom.xml, ff4j-spring-boot-autoconfigure/src/main/java/org/ff4j/spring/boot/autoconfigure/FF4JWebConfiguration.java, ff4j-spring-boot-web-api/pom.xml, ff4j-spring-boot-web-api/src/test/java/org/ff4j/spring/boot/web/api/resources/AbstractStepDef.java, ff4j-spring-services/pom.xml, pom.xml
- ff4j-spring-boot-starter
- ff4j-spring-boot-web-api
- ff4j-spring-services
- ff4j-spring-boot-autoconfigure
=> Upgraded spring-boot from 1.3.2 to 1.5.4 and spring from 4.2.3 to 4.3.9 for the following projects

ff4j-store-hazelcast/src/test/java/org/ff4j/hazelcast/CacheManagerHazelCastTest.java, ff4j-store-hazelcast/src/test/java/org/ff4j/hazelcast/store/FeatureStoreHazelCastTest.java, ff4j-store-hazelcast/src/test/java/org/ff4j/hazelcast/store/PropertyStoreHazelCastTest.java
Hopefully this will speed up the build
=> cached hazelcast object during testing to decrease test time

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java
Checking to see if auto-commit is on before attempting to commit.
This resolves issue #255  Open to other suggestions :)
=> Adding check for auto-commit for jdbc update()

ff4j-web/src/main/java/org/ff4j/web/controller/HomeController.java
I was having an error in my custom featurestore and the single line message in the UI was not really helpful in finding the root cause
=> log something when init fails!

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java, ff4j-core/src/main/java/org/ff4j/utils/JdbcUtils.java
Avoiding the following error : org.postgresql.util.PSQLException: ERROR: column "enable" is of type integer but expression is of type character varying
=> Patching update in JdbcFeatureStore.

ff4j-core/src/main/java/org/ff4j/utils/MappingUtil.java
=> Enable providing an external class loader

ff4j-core/src/main/java/org/ff4j/store/JdbcFeatureStore.java, ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java, ff4j-core/src/main/java/org/ff4j/utils/JdbcUtils.java, ff4j-core/src/test/java/org/ff4j/test/store/JdbcFeatureStoreSchemaTest.java, ff4j-store-springjdbc/src/main/java/org/ff4j/springjdbc/store/FeatureStoreSpringJdbc.java, ff4j-store-springjdbc/src/test/java/org/ff4j/test/store/SpringJdbcStoresCreateSchema.java
created property dbSchema on JdbcQueryBuilder to support sql schema such: "create table *ff4j.*FF4J_FEATURES"
as described in https://github.com/ff4j/ff4j/issues/296
=> added support with to sql schemas

pom.xml
https://github.com/ff4j/ff4j/issues/309
=> #309 Fix dependency conflict issue for org.apache.commons:commons-lang3:jar 

ff4j-store-redis/pom.xml, ff4j-store-redis/src/main/java/org/ff4j/redis/RedisConnection.java, pom.xml
I had to update Jedis driver to version 2.9.0
=> Adding SSL flag to RedisConnection

pom.xml
#336 fix dependency conflict issue for org.slf4j:slf4j-api:jar
=> fix dependency conflict issue

ff4j-core/src/main/java/org/ff4j/core/FlippingExecutionContext.java, ff4j-core/src/test/java/org/ff4j/test/FeatureTest.java
The instanceof checks break the optional support
=> Support required=false

ff4j-store-aws-ssm/pom.xml, ff4j-store-couchdb/pom.xml, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/CouchDbConnection.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/CouchDbConstants.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/CouchDbEventView.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/CouchDbFeatureView.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/CouchDbPropertyView.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbEvent.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbFeature.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbProperty.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/EventStoreCouchDb.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/FeatureStoreCouchDb.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/PropertyStoreCouchDb.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/EventStoreCouchDbTest.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/FeatureStoreCouchDBTest.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/FeatureStoreCouchDbTest.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/FeatureStoreCouchDbTest1.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/PropertyStoreCouchDbTest.java, ff4j-store-couchdb/src/test/resources/ff4j.xml, ff4j-utils-json/src/main/java/org/ff4j/utils/json/EventJsonParser.java, ff4j-utils-json/src/main/java/org/ff4j/utils/mapping/JsonStringEventMapper.java, ff4j-utils-json/src/test/java/org/ff4j/utils/json/EventJsonParserTest.java, pom.xml
Created unit tests.
Created event JSON parser.
=> Created CouchDB store for features, properties and events.

ff4j-store-aws-ssm/pom.xml, ff4j-store-consul/pom.xml, pom.xml
Upgraded java version to 1.8
Fixed ff4j-store-aws-ssm parent
=> Upgraded jackson-databind version per security alert.

ff4j-store-couchdb/pom.xml, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbEvent.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbFeature.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/document/CouchDbProperty.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/EventStoreCouchDb.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/FeatureStoreCouchDb.java, ff4j-store-couchdb/src/main/java/org/ff4j/couchdb/store/PropertyStoreCouchDb.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/EventStoreCouchDbTest.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/FeatureStoreCouchDbTest.java, ff4j-store-couchdb/src/test/java/org/ff4j/couchdb/store/PropertyStoreCouchDbTest.java
Fixed the couchdb errors created by the Jackson security update
=> Fix couchdb jackson

pom.xml
=> bump spring version

ff4j-core/src/main/java/org/ff4j/FF4j.java, ff4j-core/src/main/java/org/ff4j/core/FlippingExecutionContext.java, ff4j-web/pom.xml, ff4j-web/src/main/java/org/ff4j/web/taglib/AbstractFeatureTag.java, ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagDisable.java, ff4j-web/src/main/java/org/ff4j/web/taglib/FeatureTagEnable.java, ff4j-web/src/test/java/org/ff4j/web/taglib/FeatureTagEnableTest.java
@clun Here is a PR for #352, you can see my comments below to explain why I did it like that.
=> fix: fix execution context used in taglib

ff4j-web/src/main/resources/ff4j-messages_pt_BR.properties
Hi, this PR adds the Brazilian Portuguese i18n file for ff4j-web.
=> Issue #390 - Add brazilian portuguese support in ff4j-web

ff4j-web/src/main/resources/views/view-modal-features.html, ff4j-web/src/main/resources/views/view-modal-properties.html
Fixes #397 using [restriced mode](https://github.com/thymeleaf/thymeleaf/issues/705)
=> [issue-397] Replace in templates textual data from variables by data attributes

ff4j-store-redis/src/main/java/org/ff4j/store/EventRepositoryRedis.java
The string action parameter in method getHashKey doesn't seem to be useful, only its nullity is checked.
It is also buggy, see #399
Fix #399
=> Using the same key for storing and retrieving audit data in EventRepositoryRedis

ff4j-aop/src/main/java/org/ff4j/aop/FeatureAdvisor.java
Checking the FeatureToggle is useless when FeatureAdvisor is invoked with an alterBean or an alterClazz, because in the end we will call `mi.proceed`.
Moreover, when auditing is enable, doing this useless check will add another `checkOn` event
See #409
=> Prevent FeatureAdvisor to check FeatureToggle when invoked with either alterBean or alterClazz

ff4j-webapi/src/main/java/org/ff4j/web/api/resources/FF4jResource.java
Draft PR. Comments are welcome.
=> Add Rest API to check multiple feature toggles in one call

ff4j-store-mongodb-v3/src/main/java/org/ff4j/mongo/store/FeatureStoreMongo.java, ff4j-store-mongodb-v3/src/main/java/org/ff4j/mongo/store/PropertyStoreMongo.java
=> Fix deprecated count

ff4j-web/src/main/resources/ff4j-messages_de.properties
This PR fixes the message properties for german language on the UI.
=> fix german message properties

ff4j-store-aws-dynamodb/pom.xml, ff4j-store-aws-dynamodb/src/main/config/create-feature-dynamodb-table.json, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/DynamoDBClient.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/feature/DynamoDbFeature.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/feature/FeatureDynamoDBClient.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/feature/FeatureDynamoDBMapper.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/feature/FeatureStoreDynamoDB.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/property/DynamoDbProperty.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/property/PropertyDynamoDBClient.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/property/PropertyDynamoDBMapper.java, ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/property/PropertyStoreDynamoDB.java, ff4j-store-aws-dynamodb/src/test/java/org/ff4j/dynamodb/feature/FeatureStoreDynamoDBIT.java, ff4j-store-aws-dynamodb/src/test/java/org/ff4j/dynamodb/property/PropertyStoreDynamoDBIT.java, ff4j-store-aws-ssm/pom.xml, ff4j-store-aws-ssm/src/main/java/org/ff4j/awsssm/store/PropertyStoreAwsSSM.java, ff4j-store-aws-ssm/src/test/java/org/ff4j/awsssm/store/PropertyStoreAwsSSMTest.java
Update AWS SDK to v2 => breaking changes with previous version of the SDK
Remove deprecated constructors using tableName as a parameter => use the property file instead.
=> AWS SDK v2

ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java
... to use a set schema when creating the tables for ff4j
=> fix JdbcQueryBuilder

ff4j-core/src/main/java/org/ff4j/store/JdbcQueryBuilder.java
removed extra `+` which is causing compilation issue
=> fix: compilation issue

ff4j-core/src/main/java/org/ff4j/strategy/RegionFlippingStrategy.java, ff4j-web/src/main/resources/views/view-modal-features.html
=> Renamed To environments

ff4j-store-redis/pom.xml
Update jedis to version 3.7.0
Update lettuce-core to version 6.1.5.RELEASE
=> Redis client version upgrade

ff4j-core/src/main/java/org/ff4j/FF4j.java, ff4j-core/src/test/java/org/ff4j/test/FF4jTest.java
Introduce new FF4j class methods based on existing Store methods: existProperty, existGroup and getFeaturesByGroup
=> New FF4j class methods: existProperty, existGroup and getFeaturesByGroup

ff4j-core/src/test/java/org/ff4j/test/FF4jInitializationTest.java
Hey 😊
I want to contribute a test.
Curious to hear what you think!
(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))
=> Add test for FF4j.getCacheProxy

ff4j-web/src/main/java/org/ff4j/web/controller/HomeController.java
code changes to update file upload feature file using Jakarta Servlet3 instead of using apache commons file upload library
=> build(ff4j-web): Upgrade file upload feature to use jakarta servlet3

.github/workflows/build_workflow.yml, README.md, ff4j-store-archaius/pom.xml, ff4j-store-consul/pom.xml, ff4j-store-couchdb/pom.xml, ff4j-store-hbase/pom.xml, ff4j-store-ignite/pom.xml, ff4j-store-neo4j/pom.xml, ff4j-webapi-jersey2x/pom.xml, pom.xml
=> add enforcer and trigger ci for push to main

ff4j-config-yaml/src/main/java/org/ff4j/parser/yaml/YamlParser.java, pom.xml
=> feat: add snakeyaml 2.0 support

pom.xml
added mockito-core to test scope
Closes : #692
=> fix: marked mockito-core as test dependency

ff4j-store-redis/src/main/java/org/ff4j/store/PropertyStoreRedisLettuce.java, ff4j-store-redis/src/test/java/org/ff4j/cache/it/RedisTestSupport.java, ff4j-store-redis/src/test/java/org/ff4j/store/it/PropertyStoreRedisTestLettuceClusterIT.java
Hi ff4j team !
This small PR fixes the tests on the Redis store.
Hope this helps
Guillaume
=> fix: Ensure all redis tests are green

ff4j-core/src/main/java/org/ff4j/strategy/BlackListStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/ClientFilterStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/PonderationStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/RegionFlippingStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/ServerFilterStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/WhiteListStrategy.java, ff4j-core/src/main/java/org/ff4j/strategy/time/HourInterval.java, ff4j-core/src/main/java/org/ff4j/strategy/time/OfficeHourStrategy.java
=> docs: fix javadoc of Strategy classes

README.md
change ff4j.org to ff4j.github.io
Closes :
=> change ff4j.org to ff4j.github.io
